# Used for subscription emails (subscription_notifier.rb)
app_name: My Great App
from_email: support@example.com

# Used in account creation (account.rb)
base_domain: example.com

# Set this to true if you want to require CC info when creating a trial account for a paid plan
require_payment_info_for_trials: false

# Credit card gateway: One of brain_tree, authorize_net_cim, payment_express, or trust_commerce
gateway: brain_tree
