defaults: &defaults
  app_name: SampleApp
  from_email: support@sampleapp.com
  base_domain: sampleapp.com

  gateway: bogus
  credentials:
    gateway:
      :login: demo
      :password: password
    stripe_publishable_key:
    # PayPal sandbox account credentials go here
    paypal:
      :login: demo
      :password: password
      :signature: signature
    
development:
  <<: *defaults
  base_domain: subscriptions.dev # Edit /etc/hosts to add subscriptions.dev, test.subscriptions.dev, etc., or use Pow: http://pow.cx

test:
  <<: *defaults

production:
  <<: *defaults
  credentials:
    gateway:
      :login: demo
      :password: password
    # PayPal live account credentials go here
    paypal:
      :login: demo
      :password: password
      :signature: signature
