defaults: &defaults
  app_name: Casehawk
  from_email: demo@casehawk.com
  base_domain: herokuapp.com
  currency: USD # Only used for PayPal

  gateway: bogus
  credentials:
    gateway:
      :login: demo
      :password: password
    stripe_publishable_key:
    # PayPal sandbox account credentials go here
    paypal:
      :login: demo
      :password: password
      :signature: signature

development:
  <<: *defaults
  base_domain: casehawk.dev

test:
  <<: *defaults

production:
  <<: *defaults
  credentials:
    gateway:
      :login: demo
      :password: password
    # PayPal live account credentials go here
    paypal:
      :login: demo
      :password: password
      :signature: signature
